bet/models.py
from django.db import models
from django.contrib.auth.models import User


class Player(models.Model):
    account_number = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    full_name = models.CharField(max_length=250)
    birthday = models.DateField()
    country = models.CharField(max_length=100)
    phone = models.CharField(max_length=13, unique=True)
    balance = models.FloatField(default=0)
    frozen = models.BooleanField(default=False, blank=True)

    def __str__(self):
        return str(self.account_number)


class Operation(models.Model):
    account_number = models.ForeignKey(Player, on_delete=models.CASCADE)
    date = models.DateTimeField()
    card = models.CharField(max_length=20)
    operation_type = models.CharField(max_length=50)
    transaction_amount = models.FloatField()

    def __str__(self):
        return str(self.account_number)


class Match(models.Model):
    date = models.DateTimeField()

    def __str__(self):
        return str(self.pk)


class KindOfSport(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title


class Teams(models.Model):
    title = models.CharField(max_length=50)
    country = models.CharField(max_length=100)
    kind_sport = models.ForeignKey(KindOfSport, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Bet(models.Model):
    account_number = models.ForeignKey(Player, on_delete=models.CASCADE)
    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    date = models.DateTimeField()
    bet_team = models.ForeignKey(Teams, on_delete=models.CASCADE)
    bet_amount = models.FloatField()

    def __str__(self):
        return str(self.account_number) + " - " + str(self.match)


class MatchMembers(models.Model):
    match = models.OneToOneField(Match, on_delete=models.CASCADE, primary_key=True)
    country_id = models.ForeignKey(Teams, related_name='country_id', on_delete=models.CASCADE)
    title_id = models.ForeignKey(Teams, related_name='title_id', on_delete=models.CASCADE)

    def __str__(self):
        return str(self.match) + " : " + str(self.country_id) + " - " + str(self.title_id)

class League(models.Model):
    title = models.CharField(max_length=100)
    kind_sport = models.ForeignKey(KindOfSport, on_delete=models.CASCADE)
    year = models.IntegerField()

    def __str__(self):
        return self.title + " " + str(self.year)

class Tour(models.Model):
    match = models.OneToOneField(Match, on_delete=models.CASCADE, primary_key=True)
    league = models.ForeignKey(League, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.league) + " " + str(self.match)

class LeagueMembers(models.Model):
    league = models.ForeignKey(League, on_delete=models.CASCADE)
    team = models.ForeignKey(Teams, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.league) + " " +  str(self.team)

class Winner(models.Model):
    match = models.OneToOneField(Match, on_delete=models.CASCADE, primary_key=True)
    team = models.ForeignKey(Teams, on_delete=models.CASCADE)

class Draw(models.Model):
    match = models.OneToOneField(Match, on_delete=models.CASCADE, primary_key=True)

class MatchKoef(models.Model):
    match_id = models.IntegerField(primary_key=True)
    bet_team_id = models.IntegerField()
    perc = models.IntegerField()
    koef = models.FloatField()

    class Meta:
        managed = False
        db_table = 'match_koef'

    def __str__(self):
        return str(self.match_id) + " " + str(self.bet_team_id)

bet/templates/bet/balance.html
{% extends 'bet/base.html' %}
{% block title %}Ваш баланс{% endblock %}

{% block body %}
<style>
    #p1 {
        font-family:verdana;
        font-size:120%;
        padding-top:6px;
    }
    #td_id, #th_id {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
    }
</style>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<div class="row" >
        <div class="col-md-12" style="margin-top: 10px;margin-bottom: 10px;background-color: white;">
                <ul class="nav nav-tabs" style=" margin-left: -15px; margin-right: -15px; padding:10px; background-color: orange;">
                    <li class="active"><a data-toggle="tab" href="#home" style=" font-size:18px;">Ввод средств</a></li>
                    <li><a data-toggle="tab" href="#menu1" style=" font-size:18px;">Вывод средств</a></li>
                </ul>
                <div class="tab-content">
                    <div id="home" class="tab-pane fade in active">
                        <table class="table table-hover" style="text-align:center;font-size:16px;">
                            <thead>
                                <tr>
                                    <td style="text-align:left;"><b>Способ оплаты</b></td>
                                    <td><b>Мин. сумма</b></td>
                                    <td><b>Комиссия</b></td>
                                    <td><b>Время обработки</b></td>
                                    <td> </td>
                                </tr>
                            </thead>
                            <tr>
                                <td style="text-align:left;"><img alt="flat fee mls" title="flat fee mls" src="http://www.free-credit-card-logos.com/mc_ms_vs_accpt_h_023_gif.gif" width="113" height="30px" border="0" /> VISA/MasterCard</td>
                                <td>25.0 - &infin;</td>
                                <td>0%</td>
                                <td>моментально</td>
                                <td><a href="{% url 'user_payin' 'card' %}">
                                    <input class="btn btn-warning" style="width:100%; margin-left:3%; font-size:110%;" type="submit" value="Пополнить"></a>
                                </td>
                            </tr>
                            <tr>
                                <td style="text-align:left;"><img alt="wm" title="wm" src="https://download.webmoney.ru/WebMoney_logo_blue.svg" width="113" height="30px" border="0" /> WebMoney</td>
                                <td>50.0 - &infin;</td>
                                <td>0%</td>
                                <td>моментально</td>
                                <td><a href="{% url 'user_payin' 'wm' %}">
                                    <input class="btn btn-warning" style="width:100%; margin-left:3%; font-size:110%;" type="submit" value="Пополнить"></a>
                                </td>
                            </tr>
                            <tr>
                                <td style="text-align:left;"><img alt="mob" title="mob" src="http://ukzambians.co.uk/home/wp-content/uploads/2016/06/vodafone.jpg" width="113" height="30px" border="0" /> Vodafone</td>
                                <td>50.0 - &infin;</td>
                                <td>0%</td>
                                <td>моментально</td>
                                <td><a href="{% url 'user_payin' 'phone' %}">
                                    <input class="btn btn-warning" style="width:100%; margin-left:3%; font-size:110%;" type="submit" value="Пополнить"></a>
                                </td>
                            </tr>
                        </table>
                    </div>
                    <div id="menu1" class="tab-pane fade">
                        <table class="table table-hover" style="text-align:center;font-size:16px;">
                            <thead>
                                <tr>
                                    <td style="text-align:left;"><b>Способ вывода</b></td>
                                    <td><b>Мин. сумма</b></td>
                                    <td><b>Комиссия</b></td>
                                    <td><b>Время обработки</b></td>
                                    <td> </td>
                                </tr>
                            </thead>
                            <tr>
                                <td style="text-align:left;"><img alt="flat fee mls" title="flat fee mls" src="http://www.free-credit-card-logos.com/mc_ms_vs_accpt_h_023_gif.gif" width="113" height="100%" border="0" /> VISA/MasterCard</td>
                                <td>25.0 - &infin;</td>
                                <td>1%</td>
                                <td>1-5 минут</td>
                                <td><input class="btn btn-warning" style="width:100%; margin-left:3%; font-size:110%;" type="submit" value="Вывести"></td>
                            </tr>
                            <tr>
                                <td style="text-align:left;"><img alt="wm" title="wm" src="https://www.webmoney.ru/img/icons/88x31_wm_white_blue.png" width="113" height="100%" border="0" /> WebMoney</td>
                                <td>50.0 - &infin;</td>
                                <td>2,5%</td>
                                <td>5-10 минут</td>
                                <td><input class="btn btn-warning" style="width:100%; margin-left:3%; font-size:110%;" type="submit" value="Вывести"></td>
                            </tr>
                            <tr>
                                <td style="text-align:left;"><img alt="mob" title="mob" src="http://ukzambians.co.uk/home/wp-content/uploads/2016/06/vodafone.jpg" width="113" height="100%" border="0" /> Vodafone</td>
                                <td>50.0 - &infin;</td>
                                <td>3%</td>
                                <td>1-2 часа</td>
                                <td><input class="btn btn-warning" style="width:100%; margin-left:3%; font-size:110%;" type="submit" value="Вывести"></td>
                            </tr>
                        </table>
                    </div>
                </div>
        </div>
        <div class="col-md-12" style="margin-top: 10px;margin-bottom: 10px;background-color: white;">
                    <h2 style=" padding: 15px; margin-top: 0px;margin-bottom: 5px; margin-left: -15px; margin-right: -15px; background-color: orange;">Операции по счету:</h2>
            <div class="col-md-12">
                {% if operations %}
                <table class="table table-hover" style="text-align:center;font-size:16px;">
                    <thead>
                    <tr>
                        <td style="text-align:left;"><b>Дата</b></td>
                        <td><b>Способ пополнения</b></td>
                        <td><b>Тип операции</b></td>
                        <td><b>Сумма транзакции</b></td>
                    </tr>
                    </thead>
                    {% for op in operations %}
                    <tr>
                        <td style="text-align:left;">{{ op.date }}</td>
                        <td>{{ op.card }}</td>
                        <td>{{ op.operation_type }}</td>
                        <td>{{ op.transaction_amount }}</td>
                    </tr>
                    {% endfor %}
                </table>
                {% else %}
                <h2>Нет транзакций</h2>
                {% endif %}
            </div>
        </div>
</div>
{% endblock %}

bet/templates/bet/login.html
{% extends 'bet/base.html' %}
{% block title %}Вход{% endblock %}
{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-1 col-md-5">
        </div>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>  Вход</h3>
                    <form class="form-horizontal" role="form" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Логин:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Пароль:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <input class="btn btn-outline-secondary" name="" type="submit" value="Войти">
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Нет аккаунта? <a href="{% url 'register' %}">Нажмите сюда</a> для регистрации!
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

bet/templates/bet/match_bet.html
{% extends 'bet/base.html' %}
{% block title %}Ваш баланс{% endblock %}

{% block body %}
<style>

    #p1 {
        font-family:verdana;
        font-size:120%;
        padding-top:6px;
    }
    #td_id, #th_id {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
    }
</style>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<div class="row" >
        <div class="col-md-12" style="margin-top: 10px;margin-bottom: 10px;background-color: white;">
            {% if added %}
            <h2 align="center"><b>Ставка поставлена!</b></h2>
            {% elif error %}
            <h2 align="center"><b>{{ error }}</b></h2>
            {% else %}
            <form style="margin: 0 auto; width:100%;" class="form-horizontal" role="form" method="post" enctype="multipart/form-data">
            <div class="row">
                <h4 style=" background-color:orange; padding:5px; padding-left:20px; padding-right:20px;font-size:150%;" class="leftstr">{{ league }}</h4>
                <h4  style=" background-color:orange; padding:5px; padding-left:20px; padding-right:20px; font-size:150%;" class="rightstr">{{ league.kind_sport.title }}</h4>
                    <div class="col-md-12">
                        <table style="width:100%">
                            <tr >
                                <td id="td_id" style="width:5%; text-align:center; ">№</td>
                                <td id="td_id" style="width:5%; text-align:center; ">Дата</td>
                                <td id="td_id">Событие</td>
                                <td id="td_id">П1</td>
                                <td id="td_id">Х</td>
                                <td id="td_id">П2</td>
                            </tr>
                            <tr >
                                {% if bet %}
                                <td id="td_id" style="width:5%; text-align:center; ">{{ tour.match.pk }}</td>
                                <td id="td_id" style="width:5% text-align:center;">{{ tour.match.date|date:"d/m H:i" }}</td>
                                <td id="td_id">{{ match_memb.country_id }} - {{ match_memb.title_id }}</td>

                                <td id="td_id">
                                    {% if bet.bet_team == match_memb.country_id %}
                                        {% for m_k in match_koef %}
                                            {% if m_k.bet_team_id == match_memb.country_id.pk %}
                                            <label>{{ m_k.perc }}% - {{ m_k.koef }} {% if win.team_id == match_memb.country_id.pk %}(WIN){% endif %}</label>
                                            {% endif %}
                                        {% endfor %}
                                        <input style="margin-top:6px;float: right;" type="radio" name="bet_team" value="{{ match_memb.country_id.pk }}" checked />
                                    {% else %}
                                        {% for m_k in match_koef %}
                                            {% if m_k.bet_team_id == match_memb.country_id.pk  %}
                                            <label>{{ m_k.perc }}% - {{ m_k.koef }} {% if win.team_id == match_memb.country_id.pk %}(WIN){% endif %}</label>
                                            {% endif %}
                                        {% endfor %}
                                        <input style="margin-top:6px;float: right;" type="radio" name="bet_team" value="{{ match_memb.country_id.pk }}" disabled/>
                                    {% endif %}
                                </td>
                                <td id="td_id">
                                    {% if bet.bet_team_id == draw.pk %}
                                        {% for m_k in match_koef %}
                                            {% if m_k.bet_team_id == draw.pk  %}
                                            <label>{{ m_k.perc }}% - {{ m_k.koef }} {% if dr %}(DRAW){% endif %}</label>
                                            {% endif %}
                                        {% endfor %}
                                    <input style="margin-top:6px;float: right;" type="radio" name="bet_team" value="{{ draw.pk }}" checked/>
                                    {% else %}
                                        {% for m_k in match_koef %}
                                            {% if m_k.bet_team_id == draw.pk  %}
                                            <label>{{ m_k.perc }}% - {{ m_k.koef }} {% if dr %}(DRAW){% endif %}</label>
                                            {% endif %}
                                        {% endfor %}
                                    <input style="margin-top:6px;float: right;" type="radio" name="bet_team" value="{{ draw.pk }}" disabled/>
                                    {% endif %}
                                </td>
                                <td id="td_id">
                                    {% if bet.bet_team == match_memb.title_id %}
                                        {% for m_k in match_koef %}
                                            {% if m_k.bet_team_id == match_memb.title_id.pk  %}
                                            <label>{{ m_k.perc }}% - {{ m_k.koef }} {% if win.team_id == match_memb.title_id.pk %}(WIN){% endif %}</label>
                                            {% endif %}
                                        {% endfor %}
                                    <input style="margin-top:6px;float: right;" type="radio" name="bet_team" value="{{  match_memb.title_id.pk }}" checked />
                                    {% else %}
                                    {% for m_k in match_koef %}
                                            {% if m_k.bet_team_id == match_memb.title_id.pk  %}
                                            <label>{{ m_k.perc }}% - {{ m_k.koef }} {% if win.team_id == match_memb.title_id.pk %}(WIN){% endif %}</label>
                                            {% endif %}
                                        {% endfor %}
                                    <input style="margin-top:6px;float: right;" type="radio" name="bet_team" value="{{  match_memb.title_id.pk }}" disabled/>
                                    {% endif %}
                                </td>
                                {% else %}
                                <td id="td_id" style="width:5%; text-align:center; ">{{ tour.match.pk }}</td>
                                <td id="td_id" style="width:5% text-align:center;">{{ tour.match.date|date:"d/m H:i" }}</td>
                                <td id="td_id">{{ match_memb.country_id }} - {{ match_memb.title_id }}</td>

                                <td id="td_id">
                                    {% for m_k in match_koef %}
                                            {% if m_k.bet_team_id == match_memb.country_id.pk %}
                                            <label>{{ m_k.perc }}% - {{ m_k.koef }} {% if win.team_id == match_memb.country_id.pk %}(WIN){% endif %}</label>
                                            {% endif %}
                                        {% endfor %}
                                    <input style="margin-top:6px;float: right;" type="radio" name="bet_team" value="{{ match_memb.country_id.pk }}" required/>
                                </td>
                                <td id="td_id">
                                    {% for m_k in match_koef %}
                                            {% if m_k.bet_team_id == draw.pk %}
                                            <label>{{ m_k.perc }}% - {{ m_k.koef }} {% if dr %}(DRAW){% endif %}</label>
                                            {% endif %}
                                        {% endfor %}
                                    <input style="margin-top:6px;float: right;" type="radio" name="bet_team" value="{{ draw.pk }}" />
                                </td>
                                <td id="td_id">
                                    {% for m_k in match_koef %}
                                            {% if m_k.bet_team_id == match_memb.title_id.pk %}
                                            <label>{{ m_k.perc }}% - {{ m_k.koef }} {% if win.team_id == match_memb.title_id.pk %}(WIN){% endif %}</label>
                                            {% endif %}
                                        {% endfor %}
                                    <input style="margin-top:6px;float: right;" type="radio" name="bet_team" value="{{  match_memb.title_id.pk }}" />
                                </td>
                                {% endif %}
                            </tr>
                        </table>
                    </div>
            </div>
                    {% csrf_token %}
                    <div class="form-group" style="margin-top:15px; width:40%; position:relative; left: 30%">
                        <label   class="control-label col-md-5" for="id_bet_amount">
                            Сумма ставки:
                        </label>
                        {% if bet.bet_amount %}
                        <div  class="col-md-7">
                            <input align="right" style="width:100%;" id="id_bet_amount" min="1" name="bet_amount" type="number" value="{{ bet.bet_amount }}" placeholder="1.0" required pattern="^[ 0-9]+$" disabled >
                        </div>
                        {% else %}
                        <div  class="col-md-7">
                            <input align="right" style="width:100%;" id="id_bet_amount" min="1" name="bet_amount" type="number" placeholder="1.0" required pattern="^[ 0-9]+$" >
                        </div>
                        {% endif %}
                    </div>
                    {% if bet or win or dr or user.player.frozen %}
                    {% else %}
                    <div class="form-group" style="margin-top:15px;">
                        <div class="col-md-12">
                            <input style="margin-top:15px;margin-bottom:15px;width:40%; position:relative; left: 30%" class="btn btn-warning" name="" type="submit" value="Подтвердить ставку">
                        </div>
                    </div>
                    {% endif %}
                </form>
            {% endif %}
        </div>

</div>
{% endblock %}

bet/templates/bet/payin.html
{% extends 'bet/base.html' %}
{% block title %}Ваш баланс{% endblock %}

{% block body %}
<style>
    #p1 {
        font-family:verdana;
        font-size:120%;
        padding-top:6px;
    }
    #td_id, #th_id {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
    }
</style>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<div class="row" >
        <div class="col-md-12" style="margin-top: 10px;margin-bottom: 10px;background-color: white;">
            {% if card %}
                {% if added %}
                <p><b>Транзакция успешна!</b></p>
                {% else %}
                <h1 align="center">Введите данные карты</h1>
                <form style="margin: 0 auto; width:40%;" class="form-horizontal" role="form" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="control-label col-md-4" for="id_card">Номер карты:</label>
                        <div class="col-md-8">
                            <input style="width:100%;" id="id_card" maxlength="16" name="card" type="text" placeholder="1111222233334444" required pattern="^[ 0-9]{16}$">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-4" for="id_transaction_amount">
                                    Сумма:
                        </label>
                        <div class="col-md-8">
                            <input align="right" style="width:60%;" id="id_transaction_amount" min="25" name="transaction_amount" type="number" placeholder="25.0" required pattern="^[ 0-9]+$" >
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <input style="width:100%;" class="btn btn-warning" name="" type="submit" value="Подтвердить пополнение">
                        </div>
                    </div>
                </form>
                {% endif %}
            {% elif wm %}
             {% if added %}
                <p><b>Транзакция успешна!</b></p>
                {% else %}
                <h1 align="center">Введите данные WM счета</h1>
                <form style="margin: 0 auto; width:40%;" class="form-horizontal" role="form" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="control-label col-md-4"  for="id_card">WM счет: </label>
                        <div class="col-md-8">
                            <input style="width:100%;" id="id_card" maxlength="10" name="card" type="text" placeholder="1234567890" required pattern="^[ 0-9]{10}$">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-4" for="id_transaction_amount">
                                    Сумма:
                        </label>
                        <div class="col-md-8">
                            <input align="right" style="width:60%;" id="id_transaction_amount" min="50" name="transaction_amount" type="number" placeholder="50.0" required pattern="^[ 0-9]+$" >
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <input style="width:100%;" class="btn btn-warning" name="" type="submit" value="Подтвердить пополнение">
                        </div>
                    </div>
                </form>
            {% endif %}
            {% elif phone %}
             {% if added %}
                <p><b>Транзакция успешна!</b></p>
                {% else %}
                <h1 align="center">Введите данные телефона</h1>
                <form style="margin: 0 auto; width:40%;" class="form-horizontal" role="form" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="control-label col-md-4" for="id_card">Номер телефона:</label>
                        <div class="col-md-8">
                            <input style="width:100%;" id="id_card" maxlength="12" name="card" type="text" placeholder="380503334455" required pattern="^[ 0-9]{12}$">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-4" for="id_transaction_amount">
                                    Сумма:
                        </label>
                        <div class="col-md-8">
                            <input align="right" style="width:60%;" id="id_transaction_amount" min="50" name="transaction_amount" type="number" placeholder="50.0" required pattern="^[ 0-9]+$" >
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <input style="width:100%;" class="btn btn-warning" name="" type="submit" value="Подтвердить пополнение">
                        </div>
                    </div>
                </form>
            {% endif %}
            {% endif %}
        </div>
</div>
{% endblock %}

bet/templates/bet/register.html
{% extends 'bet/base.html' %}
{% block title %}Регистрация{% endblock %}

{% block body %}
<div class="container-fluid" style="position:relative;">

    <div class="row" >
        <div align="right" class="col-sm-1 col-md-4">
        </div>
        <div align="right" class="col-sm-1 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Регистрация нового аккаунта</h3>
                    {% if registered %}
                        <p><strong>Спасибо за регистрацию!</strong></p>
                    {% else %}
                        <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ user_form.as_p }}
                            {{ player_form.as_p }}
                            <input class="btn btn-outline-secondary" type="submit" name="" value="Register">
                        </form>
                    {% endif %}
                </div>

            </div>
        </div>
    </div>

</div>
<script>
    document.getElementById('id_email').placeholder = 'example@gmail.com';

    document.getElementById('id_phone').placeholder = '+380660001122';
</script>
{% endblock %}